# Generated by Django 3.1.1 on 2020-09-28 12:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('surname', models.CharField(max_length=64, verbose_name='Surname')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Patronymic')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='Phone number must be the following format: "+99999999"', regex='^[\\+\\d]{7,15}$$')], verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
