# Generated by Django 3.1.1 on 2020-10-01 21:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('surname', models.CharField(max_length=64, verbose_name='Surname')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Patronymic')),
                ('phone_number', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Phone number must be the following format: "+99999999"', regex='^((\\+\\d)+([0-9]){7,15})$')], verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
